# Generated by Django 5.2.8 on 2025-12-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_address_profile_city_profile_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile',
            new_name='number_phone',
        ),
    ]
